djangoproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [	
    url(r'^admin/', admin.site.urls),
    url(r'^', include('pollApp.urls', namespace='pollsNamespace')),
]

pollApp/urls.py
from django.conf.urls import url

from . import views

app_name = 'pollApp'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='indexName'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detailName'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='resultsName'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='voteName'),
]

pollApp/models.py
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')


	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pollApp/views.py
from django.shortcuts import render, get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from .models import Choice, Question
from django.utils import timezone
import datetime


class IndexView(generic.ListView):
    template_name = 'pollApp/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        
        # get the last five questions

        return Question.objects.filter( pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'pollApp/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'pollApp/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):

        # Showing the question voting form again

        return render(request, 'pollApp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        
        return HttpResponseRedirect(reverse('pollsNamespace:resultsName', args=(question.id,)))

pollApp/templates/pollApp/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>

	{% load staticfiles %}

	<link rel="stylesheet" type="text/css" href="{% static 'pollApp/css/style.css' %}">

</head>
<body>

<div class="navBar">
	<h2>Polls App</h2>
</div>

{% block content %}


{% endblock %}

</body>
</html>

pollApp/templates/pollApp/detail.html
{% extends 'pollApp/base.html' %}

{% block content %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'pollsNamespace:voteName' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<br/>
<input class="button" type="submit" value="Vote" />
</form>

{% endblock %}

pollApp/templates/pollApp/index.html
{% extends 'pollApp/base.html' %}

{% block content %}

{% if latest_question_list %}

    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'pollsNamespace:detailName' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock %}

pollApp/templates/pollApp/results.html
{% extends 'pollApp/base.html' %}

{% block content %}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a class="voteAgain" href="{% url 'pollsNamespace:detailName' question.id %}">Vote again?</a>
<a class="goBack" href="{% url 'pollsNamespace:indexName' %}">Go To Questions List</a>

{% endblock %}